version: "3"
services:
  app_backend:
    container_name: app_backend
    build: .
    ports:
      - "3000:3000"
    # network_mode: "host"
    environment:
      - PGUSER=test
      - PGPASSWORD=test
      - PGDB=testdb
      - PGHOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}
